project:
  type: book

book:
  title: "Learning Dairy"
  author: "Jane Doe"
  date: "2023/2/1"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

